"""drop_degree_ids

Revision ID: 050657818bfa
Revises: 886fc8b45fb9
Create Date: 2025-11-29 22:11:13.909548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '050657818bfa'
down_revision: Union[str, Sequence[str], None] = '886fc8b45fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'degree_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('degree_ids', sqlite.JSON(), nullable=False))
    # ### end Alembic commands ###
