"""student_time_prefs

Revision ID: 09436d1e6cc4
Revises: 050657818bfa
Create Date: 2025-12-02 22:54:48.737054

"""
import server
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09436d1e6cc4'
down_revision: Union[str, Sequence[str], None] = '050657818bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('unavailability_times', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('students', sa.Column('avoid_times', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'avoid_times')
    op.drop_column('students', 'unavailability_times')
    # ### end Alembic commands ###
