"""cleanup3

Revision ID: 29d85b65c779
Revises: 6086349db7a6
Create Date: 2025-11-29 05:59:06.032671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d85b65c779'
down_revision: Union[str, Sequence[str], None] = '6086349db7a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('degrees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('degree_works_major_code', sa.String(), nullable=False),
    sa.Column('degree_works_degree_type', sa.String(), nullable=False),
    sa.Column('degree_works_college_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('degrees')
    # ### end Alembic commands ###
