"""cleanup1

Revision ID: 343e29eefd47
Revises: 3fd82163b39f
Create Date: 2025-11-29 05:44:40.284944

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "343e29eefd47"
down_revision: Union[str, Sequence[str], None] = "3fd82163b39f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "saved_course_codes")
    op.drop_table("courses")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("courses")
    # ### end Alembic commands ###
