"""idx_course_code

Revision ID: 3a85ab316567
Revises: 1b75b24fbc35
Create Date: 2025-11-05 20:49:29.444204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a85ab316567'
down_revision: Union[str, Sequence[str], None] = '1b75b24fbc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    # ### end Alembic commands ###
