"""degree_major_change

Revision ID: 4d75ca507945
Revises: 6f6c50928852
Create Date: 2025-11-18 21:18:35.590545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d75ca507945'
down_revision: Union[str, Sequence[str], None] = '6f6c50928852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('major_code', sa.String(), nullable=False))
    op.add_column('students', sa.Column('degree_type', sa.String(), nullable=False))
    op.add_column('students', sa.Column('college', sa.String(), nullable=False))
    op.drop_column('students', 'minor')
    op.drop_column('students', 'major')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('major', sa.VARCHAR(), nullable=False))
    op.add_column('students', sa.Column('minor', sa.VARCHAR(), nullable=True))
    op.drop_column('students', 'college')
    op.drop_column('students', 'degree_type')
    op.drop_column('students', 'major_code')
    # ### end Alembic commands ###
