"""add_ratings

Revision ID: 4df9902208f2
Revises: 6acd8f643cf1
Create Date: 2025-11-06 11:19:25.465469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df9902208f2'
down_revision: Union[str, Sequence[str], None] = '6acd8f643cf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('rating_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_course_id'), 'ratings', ['course_id'], unique=False)
    op.create_index(op.f('ix_ratings_professor_id'), 'ratings', ['professor_id'], unique=False)
    op.create_index(op.f('ix_ratings_student_id'), 'ratings', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_student_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_professor_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_course_id'), table_name='ratings')
    op.drop_table('ratings')
    # ### end Alembic commands ###
