"""cleanup2

Revision ID: 6086349db7a6
Revises: 343e29eefd47
Create Date: 2025-11-29 05:47:09.478315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6086349db7a6'
down_revision: Union[str, Sequence[str], None] = '343e29eefd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attribute_ids', sa.JSON(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('major_code', sa.String(), nullable=False),
    sa.Column('course_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('major_code', 'course_number', name='uix_major_course_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    # ### end Alembic commands ###
