"""add_userinfo_columns

Revision ID: 6acd8f643cf1
Revises: 692e0dcf29d5
Create Date: 2025-11-06 00:24:58.433430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6acd8f643cf1'
down_revision: Union[str, Sequence[str], None] = '692e0dcf29d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('graduation_year', sa.Integer(), nullable=False))
    op.add_column('students', sa.Column('major', sa.String(), nullable=False))
    op.add_column('students', sa.Column('minor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'minor')
    op.drop_column('students', 'major')
    op.drop_column('students', 'graduation_year')
    # ### end Alembic commands ###
