"""cleanup4

Revision ID: 886fc8b45fb9
Revises: 29d85b65c779
Create Date: 2025-11-29 18:55:00.122877

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "886fc8b45fb9"
down_revision: Union[str, Sequence[str], None] = "29d85b65c779"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students",
        sa.Column("degree_id", sa.Integer(), nullable=False, server_default="1"),
    )
    op.drop_column("students", "major_code")
    op.drop_column("students", "college")
    op.drop_column("students", "degree_type")
    op.create_table(
        "course_attributes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("degree_works_label", sa.String(), nullable=False),
        sa.Column("courses_at_slu_label", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("courses_at_slu_label"),
        sa.UniqueConstraint("degree_works_label"),
        sa.UniqueConstraint("name"),
    )
    op.drop_table("course_sections")
    op.drop_table("mc_courses")
    op.drop_table("instructor_sections")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("degree_type", sa.VARCHAR(), nullable=False))
    op.add_column("students", sa.Column("college", sa.VARCHAR(), nullable=False))
    op.add_column("students", sa.Column("major_code", sa.VARCHAR(), nullable=False))
    op.drop_column("students", "degree_id")
    op.create_table(
        "instructor_sections",
        sa.Column("instructor_id", sa.INTEGER(), nullable=False),
        sa.Column("section_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instructor_id"],
            ["instructors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["course_sections.id"],
        ),
        sa.PrimaryKeyConstraint("instructor_id", "section_id"),
    )
    op.create_table(
        "mc_courses",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("major_code", sa.VARCHAR(), nullable=False),
        sa.Column("course_number", sa.VARCHAR(), nullable=False),
        sa.Column("attributes", sqlite.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "major_code", "course_number", name=op.f("uix_major_course_number")
        ),
    )
    op.create_table(
        "course_sections",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("course_id", sa.INTEGER(), nullable=False),
        sa.Column("crn", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("course_attributes")
    # ### end Alembic commands ###
