"""courses_sections_change

Revision ID: 9a5f1ce95d8d
Revises: 4d75ca507945
Create Date: 2025-11-20 12:35:58.133728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5f1ce95d8d'
down_revision: Union[str, Sequence[str], None] = '4d75ca507945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mc_courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('major_code', sa.String(), nullable=False),
    sa.Column('course_number', sa.String(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('major_code', 'course_number', name='uix_major_course_number')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crn', sa.String(), nullable=False),
    sa.Column('instructor_names', sa.JSON(), nullable=False),
    sa.Column('campus_code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sections')
    op.drop_table('mc_courses')
    # ### end Alembic commands ###
