"""student_desired_courses

Revision ID: f6688172ca60
Revises: 09436d1e6cc4
Create Date: 2025-12-05 15:31:30.858187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6688172ca60'
down_revision: Union[str, Sequence[str], None] = '09436d1e6cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite requires a default value when adding a NOT NULL column to existing table
    op.add_column('students', sa.Column('desired_course_ids', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'desired_course_ids')
    # ### end Alembic commands ###
